const dataSource = [
  {
    key: "1",
    taskName: "Lướt newsfeed trang chủ",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },

  {
    key: "2",
    taskName: "Xem và like story",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },

  {
    key: "3",
    taskName: "Like bài viết khi lướt",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "4",
    taskName: "Comment bài viết khi lướt",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
  },
  {
    key: "5",
    taskName: "Chia sẻ bài viết khi lướt",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
  },

  {
    key: "6",
    taskName: "Chấp nhận kết bạn",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },

  {
    key: "7",
    taskName: "Từ chối kết bạn",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "8",
    taskName: "Xem video",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "9",
    taskName: "Gửi kết bạn gợi ý",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "10",
    taskName: "Xem thông báo",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "11",
    taskName: "Đăng bài lên trang cá nhân",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
    extraOptionCheckBox: "Sao chép UID",
  },
  {
    key: "131",
    taskName: "Like bài viết vừa đăng",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "141",
    taskName: "Comment bài viết vừa đăng",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
  },
  {
    key: "12",
    taskName: "Đăng bài viết vào group",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
    extraOptionCheckBox: "Ngẫu nhiên nhóm đã chọn",
  },
  {
    key: "13",
    taskName: "Like bài viết vừa đăng",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "14",
    taskName: "Comment bài viết vừa đăng",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
  },
  {
    key: "15",
    taskName: "Tương tác chéo tài khoản",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
    extraOptionCheckBox: "Ngẫu nhiên",
  },

  {
    key: "17",
    taskName: "Like bài viết trên tường UID",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
  },
  {
    key: "18",
    taskName: "Comment bài viết trên tường UID",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
  },
  {
    key: "19",
    taskName: "Tương tác fanpage",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
    extraOptionCheckBox: "Fanpage đã like, follow",
  },
  {
    key: "20",
    taskName: "Like bài viết",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
  },
  {
    key: "17",
    taskName: "Comment bài viết có sẵn",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
  },
  {
    key: "18",
    taskName: "Tương tác nhóm",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
    extraOptionCheckBox: "Đã tham gia",
  },
  {
    key: "19",
    taskName: "Like bài viết có sẵn trong nhóm",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "20",
    taskName: "Comment bài viết có sẵn",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1", "nội dung 2"],
  },
  {
    key: "21",
    taskName: "Kết bạn với người đăng bài",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "22",
    taskName: "Like bài viết trên tường",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "23",
    taskName: "Comment bài viết trên tường",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "24",
    taskName: "Kết bạn với Tệp UID",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1"],
  },
  {
    key: "25",
    taskName: "Like bài viết của UID",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "26",
    taskName: "Comment bài viết của UID",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1"],
  },
  {
    key: "27",
    taskName: "Tham gia nhóm",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1"],
  },
  {
    key: "28",
    taskName: "Like bài viết có sẵn",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "29",
    taskName: "Comment bài viết có sẵn",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
    taskContent: ["nội dung 1"],
  },
  {
    key: "30",
    taskName: "Kết bạn với người đăng bài",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
  {
    key: "31",
    taskName: "Like bài viết trên tường",
    schedule: [1, 2],
    timePerformed: [1, 3],
    delay: 5,
  },
];

export default dataSource;
